application: zeta-rush-835
module: default
version: 1
runtime: go
api_version: go1
instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: 1s
  max_concurrent_requests: 500
handlers:
  - url: /favicon.ico
    static_files: favicon.ico
    upload: favicon.ico
  - url: /robots.txt
    static_files: robots.txt
    upload: robots.txt
  - url: /.*
    script: _go_app
